### ISSUE TITLE
Email Notifications for Resource Allocation events

### ISSUE THREAD

**Issue by Comeani** [Better-HPC/keystone-api#197]
The bank code prior to the last iteration had a system for notifying users when their proposal had either hit a threshold usage relative to the total amount awarded, or hit some threshold number of days into the proposal duration. 

Basically having some way to notify users when they need to consider submitting another Resource Allocation Request is the intention of this feature.

**Comment by Comeani** [comment]
This is becoming an increasingly high priority item, it would be good to focus on it after we have keystone's limit update functionality running in production.

**Comment by djperrefort** [comment]
User emails should come from LDAP. See https://github.com/pitt-crc/crc-ops/issues/9.

**Comment by djperrefort** [comment]
Here are some thoughts that have been kicking around a scratch page in my notebook:

## Models

Fields, relationships, and methods for each model.

| Notification |
|-|
|  <ul><li>time: DateTimeField</li><li>message: TextField</li><li>read: BooleanField</li></ul> |
| <ul><li> user: ForiegnKey(User)</li></ul> |
| |

| Preference |
|-|
|  <ul><li>alloc_thresholds:ArrayField(IntegerField) </li><li>alloc_status_update: BooleanField</li><li>expiration: BooleanField</li><li> anything else of use ...</li></ul> |
| <ul><li> user: OneToOneField(User)</li></ul> |
| |

| DefaultPreference* |
|-|
|  <ul><li>su_thresholds:ArrayField(IntegerField) </li><li>expiration: BooleanField</li></ul> |
|  |
|  |

\* This table should be a singleton that only ever stores one record.

## Shortcuts

Functions that go inside `shortcuts.py`.

```python
def notify(user: User, message: str) -> None:
    # fetch email address from User table
    # send email (or log error)
    # update notification DB
```

## Endpoints

The endpoints are mostly structured he same way we set up every other app with two exceptions:

1. Instead of `/defaults/` and `/defaults/<pk>`, there is only a single endpoint `/defaults` which returns default settings
2. We should think of the preferred workflow for fetching a user's preferences given their username/UID. The default `prferences/<pk>` may be cumbersome.

**Comment by djperrefort** [comment]
Also, it's worth noting in the above that I have used an array field, which means we would have to drop support for SQLite and run PostgreSQL exclusively.

**Comment by Comeani** [comment]
#307 is relevant to this issue, we should see how user alerts might fit into email notifications as we build them out.

**Comment by djperrefort** [comment]
Dropping the following thought as a note to myt future self:

```python
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

def send_expiration_notifications():
    
    # Get all allocation requests that have expired
    # We may want to limit this to recently expired allocations to prevent a barrage of emails
    expired_requests = AllocationRequest.objects.filter(expire__lt=timezone.now())

    for request in expired_requests:
        for user in request.group.all_members():

            # Add logic here to check the user's notification preferences

            notification_sent = Notification.objects.filter(
                user=user,
                notification_type=Notification.NotificationType.request_status,
                metadata__request_id=request.id
            ).exists()

            if not notification_sent:
                # Create and send a notification
                notification = Notification.objects.create(
                    user=user,
                    message=f"Your allocation request '{request.title}' has expired.",
                    metadata={'request_id': request.id},
                    notification_type=Notification.NotificationType.request_status
                )
```

**Comment by djperrefort** [comment]
#### Todo

Notify users when:

- [ ] allocations are approved/denied
- [x] allocations are expiring
- [ ] allocations nearing exhaustion
